#' Annotate Cells with Concentric Circle Radius Bins
#'
#' Assigns each cell to the smallest concentric circle radius that contains
#' it by performing a spatial join between cell coordinates and concentric
#' circle geometries. Radius annotations are merged back into the parent
#' Xenium object and can optionally be saved for downstream analyses.
#'
#' @param xenium.obj A Seurat Xenium object containing cell metadata.
#' @param data Data frame containing spatial coordinates and cell metadata.
#' Must contain columns \code{cell_ID}, \code{x.coord}, and
#' \code{y.coord}.
#' @param concentric_circles_sf An sf object containing concentric circle
#' geometries generated by \code{generate_concentric_circles()}.
#' @param save_output Logical. If TRUE, save the annotated metadata and
#' updated Xenium object as RDS files.
#' @param metadata_file Character string specifying the filename used to save
#' merged metadata.
#' @param xeniumObj_file Character string specifying the filename used to save
#' the updated Xenium object.
#' 
#' @importFrom rlang .data
#'
#' @return A list containing:
#' \describe{
#' \item{xenium_cells_annotated}{sf object after spatial radius assignment.}
#' \item{xenium_cells_clean_binned}{Data frame containing one radius assignment per cell after removing duplicate assignments.}
#' \item{meta.xenium.merge}{Merged metadata containing radius annotations for all cells.}
#' \item{xenium.obj}{Updated Xenium object with \code{radius.concentric.sf} metadata added.}
#' }
#'
#' @details
#' Cells are converted into sf point geometries using the
#' \code{x.coord} and \code{y.coord} coordinates. A spatial join is
#' performed against the concentric circle polygons, and if a cell is
#' assigned to multiple radii, only the smallest radius is retained.
#' The resulting radius annotation is stored as
#' \code{radius.concentric.sf}.
#'
#' Cells that do not fall within any concentric circle are assigned
#' \code{NA} for \code{radius.concentric.sf}.
#'
#' @export

# Function to annotate metadata with radius bins
annotate_radius_bins_xenium <- function(xenium.obj, data, concentric_circles_sf, save_output = TRUE, metadata_file = "meta.xenium.merge.rds", xeniumObj_file="XeniumfullObject_sfConcCircles.rds") {
  
  # Filter out NAs as they are not tolerated by sf_as_sf()
  data <- data |> dplyr::filter(!is.na(x.coord),
                                !is.na(y.coord))
  
  # Convert xenium.cells.3 to sf points using shifted x.coord
  xenium_cells_sf <- data |>
    sf::st_as_sf(coords = c("x.coord", "y.coord"), crs = sf::NA_crs_)
  
  
  # Spatial join to assign each cell the radius it falls within
  xenium_cells_annotated <- sf::st_join(xenium_cells_sf, concentric_circles_sf, join = sf::st_within)
  
  # Drop geometry and remove duplicate cell assignments by keeping smallest radius
  # Convert back to data frame
  xenium_cells_clean_binned <- xenium_cells_annotated |>
    sf::st_drop_geometry() |>
    dplyr::group_by(.data$cell_ID) |>
    dplyr::slice_min(radius, with_ties = FALSE) |> # keep only the smallest radius match
    dplyr::ungroup()
  
  # Filter for cells that fall WITHIN the concentric circle regions
  xenium_cells_annotated_df <- xenium_cells_clean_binned |> dplyr::filter(!is.na(.data$radius))
  
  # Check if any of the cells are double annotated
  message(
    "Any duplicated cells: ",
    any(duplicated(xenium_cells_annotated_df$cell_ID))
  )
  
  # Prep metadata to be added back to parent Xenium object
  # First, get all parent object cell ID for downstream merging
  print("______________Now adding metadata back to parent Xenium object______________")
  md <- as.data.frame(xenium.obj[[]])
  
  # Make rownames as cell_ID
  md$cell_ID <- rownames(md)
  
  # Subset columns for merging
  meta.xenium <- md |> dplyr::select(.data$cell_ID, .data$orig.ident)
  
  # Merge xenium_cells_annotated_df with meta.xenium
  meta.xenium.merge <- dplyr::left_join(meta.xenium, xenium_cells_annotated_df[c("cell_ID", "radius")], by="cell_ID")
  
  # Rename radius column
  meta.xenium.merge <- dplyr::rename(meta.xenium.merge, "radius.concentric.sf"="radius")
  

  # Add radius bins back to parent Xeium object
  xenium.obj <- Seurat::AddMetaData(xenium.obj,
                            meta.xenium.merge[,c("cell_ID","radius.concentric.sf")],
                            col.name = c("cell_ID","radius.concentric.sf"))
  
  if (isTRUE(save_output)) {
    
  # Export merged metadata
    print("Saving merged metadata as RDS")
    saveRDS(meta.xenium.merge, metadata_file)
  
  
  
  # Save new parent Xenium object
    print("Saving Xenium object as RDS")
    saveRDS(xenium.obj, xeniumObj_file)
  
  }
  
  result <- list(
    xenium_cells_annotated = xenium_cells_annotated,
    xenium_cells_clean_binned = xenium_cells_clean_binned,
    meta.xenium.merge = meta.xenium.merge,
    xenium.obj = xenium.obj
  )
  
  return(invisible(result))
  
}


