#' Label radius groups as Peritumoral and Distal Regions
#'
#' Assigns concentric circle radii into biologically meaningful spatial
#' regions (Tumor, Peritumoral, and Distal), generates region-level metadata,
#' and visualizes the corresponding boundary rings on spatial coordinates.
#'
#' @param data Data frame containing spatial coordinates. Typically
#'   \code{res.conc$xenium.sub}.
#' @param meta.xenium.merge Data frame containing concentric circle radius
#'   annotations for each cell.
#' @param tumor.radius Radius defining the tumor boundary.
#' @param peritumoral.radius Radius defining the peritumoral boundary.
#' @param distal.radius Radius defining the distal boundary.
#' @param concentric_circles_sf sf object containing concentric circle
#'   geometries generated by \code{generate_concentric_circles()}.
#' @param center_point_sfc sf point object representing the tumor centroid.
#' @param g.title Plot title.
#' @param tumor.conc.color Color used for the tumor boundary.
#' @param peritumoral.conc.color Color used for the peritumoral boundary.
#' @param distal.conc.color Color used for the distal boundary.
#' @param save_output Logical; whether to save generated output
#'   (RDS).
#' @param save_plot Logical; whether to save generated plot
#'   (PNG plot).
#' @param plot_file Output PNG filename used when
#'   \code{save_plot = TRUE}.
#'
#' @return A list containing:
#' \describe{
#'   \item{meta.merge.peri}{Metadata with radius-group labels and spatial region assignments.}
#'   \item{label.check}{Summary table used to verify region assignments.}
#'   \item{data.merge}{Cell metadata merged with spatial region labels.}
#'   \item{radius_map}{Mapping of radii to spatial regions.}
#'   \item{boundary_sf}{sf object containing tumor, peritumoral, and distal boundary rings.}
#'   \item{concCircle.plot.radius}{ggplot object showing colored spatial boundaries.}
#' }
#'
#' @export


# Function to annotate metadata with radius bins
label_peritumoral_distal_xenium <- function(data, meta.xenium.merge, tumor.radius=1000, peritumoral.radius=2800, distal.radius=7400, concentric_circles_sf, center_point_sfc, g.title="Concentric Circles with Colored Boundaries", tumor.conc.color="darkred", peritumoral.conc.color="goldenrod", distal.conc.color="darkolivegreen4", save_output = TRUE, save_plot = TRUE, plot_file = "concentricSemiCircle_peritumoralDistalGroupColored.png"){
  
  # Categorize radius groups into peritumoral vs distal
  df <- as.data.frame(meta.xenium.merge)
  meta.xenium.merge.clean <- df |> dplyr::filter(!is.na(radius.concentric.sf))
  
  # Check radius group and corresponding distance
  rad.check <- table(meta.xenium.merge.clean$radius.concentric.sf) |> as.data.frame()
  rad.check$num <- row.names(rad.check)
  
  # Label radius groups as peritumoral vs distal boundaries
  ## ensure NA is NA (not "NA" string)
  meta.xenium.merge.clean <- meta.xenium.merge.clean |>
    dplyr::mutate(distance.group = dplyr::case_when(
      radius.concentric.sf == tumor.radius ~ "Tumor",
      radius.concentric.sf == peritumoral.radius ~ "Peritumoral",
      radius.concentric.sf == distal.radius ~ "Distal",
      TRUE ~ NA_character_
    ))
  
  
  # Create a new metadata with radius group labeling for export---
  meta.merge.peri.temp <- meta.xenium.merge.clean
  
  num.label <- unique(c(meta.merge.peri.temp$radius.concentric.sf)) |> sort()
  names(num.label) <- paste0("radius.group.", seq_along(num.label))
  num.df <- data.frame(
    radius_group_label = names(num.label),
    num.label = unname(num.label),
    row.names = NULL
  )
  
  meta.merge.peri <- merge(meta.merge.peri.temp, num.df, by.x="radius.concentric.sf", by.y="num.label")
  meta.merge.peri <- meta.merge.peri |> dplyr::mutate(peri_distal_group_label = dplyr::case_when(radius.concentric.sf <= tumor.radius ~ "Tumor", radius.concentric.sf <= peritumoral.radius ~ "Peritumoral", radius.concentric.sf <= distal.radius ~ "Distal")) 
  # Get rid of distance.group column
  meta.merge.peri <- meta.merge.peri |> dplyr::select(-distance.group)

  
  # Save meta.merge.peri
  if (isTRUE(save_output)) {
    
    print("Saving meta.merge.peri as RDS")
    
    saveRDS(
      meta.merge.peri,
      "meta.merge.peri.rds"
    )
    
  }
  
  
  
  # Double check labeling
  label.check <- meta.xenium.merge.clean |> dplyr::group_by(distance.group, radius.concentric.sf) |> dplyr::count() |> as.data.frame()
  
  # Merge peritumoral vs distal with xenium.sub
  data.merge <- dplyr::left_join(data, meta.xenium.merge.clean, by="cell_ID")
  
  
  # Add distance.group to the ring sf
  # radius -> distance.group mapping from your merged table
  radius_map <- meta.xenium.merge.clean |>
    dplyr::filter(!is.na(radius.concentric.sf), !is.na(distance.group)) |>
    dplyr::distinct(radius = radius.concentric.sf, distance.group)
  
  
  ## attach map; also make a boundary-only sf
  concentric_circles_sf_grp <- sf::st_as_sf(concentric_circles_sf)
  
  concentric_circles_sf_grp <- concentric_circles_sf_grp |>
    dplyr::left_join(radius_map, by = "radius") |>
    dplyr::mutate(distance.group = factor(distance.group,
                                   levels = c("Tumor", "Peritumoral", "Distal")))
  
  
  
  # keeps only tumor, peritumoral, distal radius
  boundary_sf <- concentric_circles_sf_grp |>
    dplyr::filter(!is.na(distance.group))  
  
  ## plot peritumoral and distal groups
  concCircle.plot.radius <- ggplot2::ggplot() +
    # cells
    ggplot2::geom_point(data = data,
                        ggplot2::aes(x = x.coord, y = y.coord),
               color = "black", size = 0.001, alpha = 0.1) +
    
    # base: all rings uncolored (neutral)
    ggplot2::geom_sf(data = concentric_circles_sf, fill = NA,
            color = "grey70", linewidth = 0.4, alpha = 0.8, inherit.aes = FALSE) +
    
    # overlay: only boundary rings colored
    ggplot2::geom_sf(data = boundary_sf, ggplot2::aes(color = distance.group),
            fill = NA, linewidth = 1.4, alpha = 1, show.legend = TRUE) +
    
    # tumor center
    ggplot2::geom_sf(data = center_point_sfc, color = "red", size = 3, shape = 8, inherit.aes = FALSE) +
    
    ggplot2::labs(title = g.title,
         x = "X Coordinate", y = "Y Coordinate", color = "Boundary") +
    ggplot2::scale_colour_manual(values = c("Tumor" = tumor.conc.color,
                                   "Peritumoral"    = peritumoral.conc.color,
                                   "Distal"         = distal.conc.color),
                        drop = FALSE) +
    ggplot2::theme_bw() +
    ggplot2::coord_sf()
  
  concCircle.plot.radius
  
  if (isTRUE(save_plot)) {
    
    print("Saving plot as PNG")
    
    ggplot2::ggsave(concCircle.plot.radius, filename = plot_file, width = 8, height = 10, units = "in", dpi = 300)
    
  }
  
  return(invisible(list(concCircle.plot.radius = concCircle.plot.radius)))
  
  
}

