#' Plot Concentric Circles Colored by Radius
#'
#' Visualizes concentric circles generated by
#' \code{generate_concentric_circles()} with each radius displayed using a
#' viridis color scale. Spatial cell coordinates are shown in the background,
#' concentric circles are colored according to their radius, and the tumor
#' centroid is indicated by a red marker.
#'
#' @param data Data frame containing spatial coordinates. Typically
#'   \code{res.conc$xenium.sub}.
#' @param Tumor Character string specifying the tumor annotation label.
#'   Used for naming the output file.
#' @param concentric_circles_sf sf object containing concentric circle
#'   geometries generated by \code{generate_concentric_circles()}.
#' @param center_point_sfc sf point object representing the tumor centroid.
#' @param g.title Plot title.
#' @param scale.viridis.option Viridis color palette option. One of
#'   \code{"A"}, \code{"B"}, \code{"C"}, \code{"D"}, or \code{"F"}.
#' @param save_plot Logical; whether to save the generated plot as a PNG file.
#' @param plot_file Output filename used when \code{save_plot = TRUE}.
#'
#' @return A list containing:
#' \describe{
#'   \item{concCircle.plot.radius}{ggplot object containing the radius-colored spatial plot.}
#' }
#'
#' @export


# Function to plot concentric circles with colored radii
plot_concCircle_colorRadii_giotto <- function(data, Tumor = "Tumor.1", concentric_circles_sf, center_point_sfc, g.title="Concentric Circles emanating from Tumor Center", scale.viridis.option=c("C", "A", "B", "D", "F"), save_plot = TRUE, plot_file="concentricSemiCircle-Tumor-center_coloredRadii.png"){
  
  # SAFE-PROOF: Automatically grabs the first viridis.option string (or defaults to "magma")
  scale.viridis.option <- match.arg(scale.viridis.option)
  

  # Get metadata
  df <- as.data.frame(data)
  
  concCircle.plot.radius <- ggplot2::ggplot() +
    ggplot2::geom_point(data = df, ggplot2::aes(x = x.coord.shift, y = y.coord), color="black", size = 0.001, alpha = 0.1) +
    ggplot2::geom_sf(data = concentric_circles_sf, fill=NA, ggplot2::aes(color= factor(radius)), alpha = 1, linewidth=1.2) +
    ggplot2::geom_sf(data = center_point_sfc, color = "red", size = 3, shape = 8) +
    ggplot2::labs(title = g.title,
         x = "X Coordinate", y = "Y Coordinate",
         fill = "Radius") +
    ggplot2::theme_bw() + 
    viridis::scale_colour_viridis(discrete=TRUE, option= scale.viridis.option) +
    ggplot2::coord_sf()
  
  
  if (isTRUE(save_plot)) {
    
    print("Saving plot as PNG")
    
    ggplot2::ggsave(filename = plot_file, plot = concCircle.plot.radius, width = 8, height = 10, units = "in", dpi = 300)  
    
  }
  
  result <- list(concCircle.plot.radius = concCircle.plot.radius)
  
  return(invisible(result))

}


