#' Plot Concentric Circles with Cell Annotations
#'
#' Visualizes concentric circles generated by
#' \code{generate_concentric_circles()} overlaid on spatial cell coordinates.
#' Cells are colored according to the specified annotation column and the
#' selected tumor annotation can be highlighted with a custom color.
#'
#' @param data Data frame containing spatial coordinates and cell annotation
#'   metadata. Typically \code{res.conc$xenium.sub}.
#' @param concentric_circles_sf sf object containing concentric circle
#'   geometries generated by \code{generate_concentric_circles()}.
#' @param center_point_sfc sf point object representing the tumor centroid.
#' @param L.annot Character string specifying the metadata column used for
#'   cell annotation.
#' @param Tumor Character string specifying the tumor annotation label.
#' @param tumor.color Color used to highlight the tumor annotation.
#' @param viridis.option Viridis palette option. One of
#'   \code{"magma"}, \code{"inferno"}, \code{"plasma"},
#'   \code{"viridis"}, or \code{"rocket"}.
#' @param save_plot Logical; whether to save the generated plot as a PNG file.
#' @param plot_file Output plot as PNG.
#' @importFrom rlang .data
#' 
#'
#' @return A list containing:
#' \describe{
#'   \item{l3.annot_colors}{Named vector of annotation colors.}
#'   \item{concCircle.plot}{ggplot object containing the spatial plot.}
#' }
#'
#' @export

# Function to plot concentric circles and all cell annotations
plot_concCircle_cellAnnot_giotto <- function(data , concentric_circles_sf, center_point_sfc, L.annot="L3.annot", Tumor = "Tumor.1", tumor.color = "springgreen3", viridis.option =c("magma", "inferno", "plasma", "viridis", "rocket"), save_plot = TRUE, plot_file = "concentricSemiCircle-Tumor-center.png"){
  
  # SAFE-PROOF: Automatically grabs the first viridis.option string (or defaults to "magma")
  viridis.option <- match.arg(viridis.option)
  
  
  # Get metadata
  df <- as.data.frame(data)
  
  # Generate viridis colors for annotations
  l3.annot_colors <- viridis::viridis_pal(option = viridis.option)(length(unique(df[[L.annot]]))) 
  names(l3.annot_colors) <- unique(df[[L.annot]])
  
  
  # Customize tumor color
  l3.annot_colors[Tumor] <- tumor.color
  
  
  concCircle.plot <- ggplot2::ggplot() +
    ggplot2::geom_point(data = df, ggplot2::aes(x = x.coord.shift, y = y.coord, color = .data[[L.annot]]), size = 0.001, alpha = 0.1) +
    ggplot2::geom_sf(data = concentric_circles_sf, fill = NA, color = "black", alpha = 0.9) +
    ggplot2::geom_sf(data = center_point_sfc, color = "red", size = 3, shape = 8) +
    ggplot2::labs(title = "Concentric Circles emanating from Tumor Center",
         x = "X Coordinate", y = "Y Coordinate",
         fill = "Radius") +
    ggplot2::theme_bw() + 
    ggplot2::guides(color = "none") +
    ggplot2::scale_colour_manual(values=l3.annot_colors) +
    ggplot2::coord_sf()
  

  # Save outputs as png
  if (isTRUE(save_plot)) {
    
    print("Saving plot as PNG")
    
    ggplot2::ggsave(filename = plot_file, plot = concCircle.plot, width = 8, height = 10, units = "in", dpi = 300)
    
  }
  
  result <- list(
    l3.annot_colors = l3.annot_colors,
    concCircle.plot = concCircle.plot
  )
  
  
  return(invisible(result))
}



